# Generated by Django 5.2.5 on 2025-08-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can Send Private Email')]},
        ),
    ]
